### ISSUE TITLE
is there anything like this for older versions?

### ISSUE THREAD

**Issue by gittohabbuu** [DaPhysikist/Leashable-Boats#3]
I'd love to see something like this for versions like 1.12 or 1.16 but this was the only mod I found that adds this to the game.

**Comment by DaPhysikist** [comment]
Unfortunately, there is not, which is why I decided to make this mod. Creating releases for older versions is something I could look into for the future.

**Comment by gittohabbuu** [comment]
> Unfortunately, there is not, which is why I decided to make this mod. Creating releases for older versions is something I could look into for the future.

I see, thanks for the answer! will be looking forward to maybe backports to older versions coming
